version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The ESHOP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     ESHOP_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file

services:

  maildev:
    ports:
      - "5500:1080"
      - "1025:1025"

  rabbitmq:
    ports:
      - "5672:5672"

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - eshop-sqldata:/var/opt/mssql

  zipkin:
    ports:
      - "5411:9411"

  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://identity.localhost:8080
      - SeqServerUrl=http://seq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.basket-api.rule=Host(`basket.localhost:8080`)"
      - "traefik.http.routers.basket-api.entrypoints=web"
      - "traefik.http.services.basket-api.loadbalancer.server.port=80"

  blazor-client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ApiGatewayUrlExternal=http://webshoppingapigw.localhost:8080
      - IdentityUrlExternal=http://identity.localhost:8080
      - SeqServerUrl=http://seq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blazor-client.rule=Host(`blazor-client.localhost:8080`)"
      - "traefik.http.routers.blazor-client.entrypoints=web"
      - "traefik.http.services.blazor-client.loadbalancer.server.port=80"

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - SeqServerUrl=http://seq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catalog-api.rule=Host(`catalog.localhost:8080`)"
      - "traefik.http.routers.catalog-api.entrypoints=web"
      - "traefik.http.services.catalog-api.loadbalancer.server.port=80"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SeqServerUrl=http://seq
      - RetryMigrations=true
      - IssuerUrl=http://identity.localhost:8080
      - BlazorClientUrlExternal=http://blazor-client.localhost:8080
      - BasketApiUrlExternal=http://basket-api.localhost:8080
      - OrderingApiUrlExternal=http://ordering-api.localhost:8080
      - ShoppingAggregatorApiUrlExternal=http://webshoppingagg.localhost:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.identity-api.rule=Host(`identity.localhost:8080`)"
      - "traefik.http.routers.identity-api.entrypoints=web"
      - "traefik.http.services.identity-api.loadbalancer.server.port=80"

  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://identity.localhost:8080
      - RetryMigrations=true
      - SeqServerUrl=http://seq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ordering-api.rule=Host(`ordering.localhost:8080`)"
      - "traefik.http.routers.ordering-api.entrypoints=web"
      - "traefik.http.services.ordering-api.loadbalancer.server.port=80"

  payment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SeqServerUrl=http://seq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment-api.rule=Host(`payment.localhost:8080`)"
      - "traefik.http.routers.payment-api.entrypoints=web"
      - "traefik.http.services.payment-api.loadbalancer.server.port=80"

  webshoppingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://identity.localhost:8080
      - SeqServerUrl=http://seq
      - BasketUrlHC=http://basket-api/hc
      - CatalogUrlHC=http://catalog-api/hc
      - IdentityUrlHC=http://identity-api/hc
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webshoppingagg-api.rule=Host(`webshoppingagg.localhost:8080`)"
      - "traefik.http.routers.webshoppingagg-api.entrypoints=web"
      - "traefik.http.services.webshoppingagg-api.loadbalancer.server.port=80"

  webshoppingapigw:
    environment:
      - ENVOY_CATALOG_API_ADDRESS=catalog-api
      - ENVOY_CATALOG_API_PORT=80
      - ENVOY_ORDERING_API_ADDRESS=ordering-api
      - ENVOY_ORDERING_API_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webshoppingapigw-api.rule=Host(`webshoppingapigw.localhost:8080`)"
      - "traefik.http.routers.webshoppingapigw-api.entrypoints=web"
      - "traefik.http.services.webshoppingapigw-api.loadbalancer.server.port=80"

  webstatus:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=Basket API
      - HealthChecksUI__HealthChecks__0__Uri=http://basket-api/hc
      - HealthChecksUI__HealthChecks__1__Name=Catalog API
      - HealthChecksUI__HealthChecks__1__Uri=http://catalog-api/hc
      - HealthChecksUI__HealthChecks__2__Name=Identity API
      - HealthChecksUI__HealthChecks__2__Uri=http://identity-api/hc
      - HealthChecksUI__HealthChecks__3__Name=Ordering API
      - HealthChecksUI__HealthChecks__3__Uri=http://ordering-api/hc
      - HealthChecksUI__HealthChecks__4__Name=Payment API
      - HealthChecksUI__HealthChecks__4__Uri=http://payment-api/hc
      - HealthChecksUI__HealthChecks__5__Name=Web Shopping Aggregator
      - HealthChecksUI__HealthChecks__5__Uri=http://webshoppingagg/hc
      - HealthChecksUI__HealthChecks__6__Name=Blazor UI Host
      - HealthChecksUI__HealthChecks__6__Uri=http://blazor-client/hc
    ports:
      - "5107:80"



